
import { Trade, User, Notification, MessageThread } from './types';
import { PlaceHolderImages } from './placeholder-images';

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    name: 'Alex Rivera',
    handle: 'arivera_trades',
    avatar: PlaceHolderImages[0].imageUrl,
    verified: true,
    bio: 'Macro options trader focused on tech and energy sectors. 10 years in the game.',
    joinedDate: '2021-03-12',
    followers: 12400,
    following: 156,
  },
  {
    id: 'u2',
    name: 'Sarah Chen',
    handle: 'optionsqueen',
    avatar: PlaceHolderImages[1].imageUrl,
    verified: true,
    bio: 'Volatility specialist. Selling premium and managing risk. I love iron condors.',
    joinedDate: '2022-01-05',
    followers: 8900,
    following: 432,
  },
  {
    id: 'u3',
    name: 'Market Whiz',
    handle: 'marketwhiz',
    avatar: PlaceHolderImages[2].imageUrl,
    bio: 'Searching for whales and unusual options activity. Data-driven only.',
    joinedDate: '2023-11-20',
    followers: 3200,
    following: 89,
  },
  {
    id: 'u4',
    name: 'John Doe',
    handle: 'johndoe_trading',
    avatar: 'https://picsum.photos/seed/jd/200/200',
    bio: 'Professional coffee drinker and part-time index trader.',
    joinedDate: '2024-02-14',
    followers: 120,
    following: 45,
  }
];

export const MOCK_TRADES: Trade[] = [
  {
    id: 't1',
    user: MOCK_USERS[0],
    ticker: 'AAPL',
    optionType: 'call',
    strikePrice: 245,
    expirationDate: '2025-06-20',
    size: 50,
    price: 12.45,
    timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    sentiment: 'bullish',
    returnPercentage: 145,
  },
  {
    id: 't2',
    user: MOCK_USERS[1],
    ticker: 'TSLA',
    optionType: 'put',
    strikePrice: 190,
    expirationDate: '2025-04-18',
    size: 200,
    price: 8.12,
    timestamp: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    sentiment: 'bearish',
    returnPercentage: 82,
  },
  {
    id: 't3',
    user: MOCK_USERS[2],
    ticker: 'NVDA',
    optionType: 'call',
    strikePrice: 155,
    expirationDate: '2025-05-16',
    size: 15,
    price: 145.20,
    timestamp: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    sentiment: 'bullish',
    returnPercentage: 420,
  },
  {
    id: 't4',
    user: MOCK_USERS[0],
    ticker: 'META',
    optionType: 'call',
    strikePrice: 620,
    expirationDate: '2025-03-21',
    size: 100,
    price: 45.60,
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    sentiment: 'bullish',
    returnPercentage: 12,
  },
  {
    id: 't5',
    user: MOCK_USERS[1],
    ticker: 'AMZN',
    optionType: 'put',
    strikePrice: 175,
    expirationDate: '2025-04-11',
    size: 75,
    price: 3.25,
    timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    sentiment: 'bearish',
    returnPercentage: -15,
  },
  {
    id: 't6',
    user: MOCK_USERS[0],
    ticker: 'NVDA',
    optionType: 'put',
    strikePrice: 130,
    expirationDate: '2025-03-28',
    size: 25,
    price: 4.15,
    timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    sentiment: 'bearish',
    returnPercentage: 310,
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    type: 'like',
    user: MOCK_USERS[0],
    message: 'liked your trade on $AAPL',
    timestamp: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    read: false,
    tradeId: 't1',
  },
  {
    id: 'n2',
    type: 'follow',
    user: MOCK_USERS[1],
    message: 'started following you',
    timestamp: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    read: false,
  },
  {
    id: 'n3',
    type: 'repost',
    user: MOCK_USERS[2],
    message: 'reposted your whale alert on $NVDA',
    timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    read: true,
    tradeId: 't3',
  },
  {
    id: 'n4',
    type: 'system',
    message: 'Welcome to TradeStream! Start following top traders to see their activity.',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    read: true,
  },
  {
    id: 'n5',
    type: 'like',
    user: MOCK_USERS[1],
    message: 'liked your trade on $TSLA',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    read: true,
    tradeId: 't2',
  }
];

export const MOCK_MESSAGE_THREADS: MessageThread[] = [
  {
    id: 'm1',
    user: MOCK_USERS[0],
    lastMessage: 'Did you see that volume on $NVDA calls? Absolute insanity.',
    timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    unread: true,
  },
  {
    id: 'm2',
    user: MOCK_USERS[1],
    lastMessage: 'The iron condor strategy is working perfectly in this range.',
    timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    unread: false,
  },
  {
    id: 'm3',
    user: MOCK_USERS[2],
    lastMessage: 'Thanks for the alert! Followed that whale into the $META trade.',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    unread: false,
  }
];
